Work around an unfortunate 2->3 behavior change in argparse.
Invoking it without any arguments under python3 had been leading to an
exception:

  AttributeError: 'Namespace' object has no attribute 'action'

Now it gives the proper missing-required-argument error from argparse,
as it did/does under python2.